"""Idempotent database seed script for development.

Populates the database with Faker-generated sample data:
- 5 teams (>= 3 required)
- 5-10 members per team (random, within 5-10 range)
- 2-3 repos per team
- 3-5 commits per developer (random, within 3-5 range)
- 2-4 audit logs per team

All data is generated by Faker — no real user information is used.

Usage:
    python seed.py

The script is idempotent — it first deletes existing seed data in
dependency order, then inserts fresh data.
"""

import asyncio
import hashlib
import sys
from datetime import UTC, datetime, timedelta
from uuid import uuid4

from faker import Faker
from sqlalchemy import delete
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import hash_password
from app.db.models.audit_log import AuditLog
from app.db.models.commit import Commit
from app.db.models.repo import Repo
from app.db.models.repo_member import RepoMember
from app.db.models.team import Team
from app.db.models.team_member import TeamMember
from app.db.models.user import User
from app.db.session import AsyncSessionLocal, engine

fake = Faker()
Faker.seed(42)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

NUM_TEAMS = 5
MIN_MEMBERS_PER_TEAM = 5
MAX_MEMBERS_PER_TEAM = 10
MIN_REPOS_PER_TEAM = 2
MAX_REPOS_PER_TEAM = 3
MIN_COMMITS_PER_DEVELOPER = 3
MAX_COMMITS_PER_DEVELOPER = 5
MIN_AUDIT_LOGS_PER_TEAM = 2
MAX_AUDIT_LOGS_PER_TEAM = 4

ROLES = ["admin", "developer", "developer", "developer", "viewer"]

COMMIT_TYPES = ["feat", "fix", "refactor", "docs", "test", "chore", "perf", "style"]
COMMIT_SCOPES = [
    "auth",
    "api",
    "db",
    "ui",
    "config",
    "middleware",
    "models",
    "routes",
    "services",
    "utils",
]
COMMIT_SUBJECTS = [
    "add new endpoint",
    "resolve null pointer issue",
    "simplify session handling",
    "update documentation",
    "add integration tests",
    "upgrade dependencies",
    "optimize query performance",
    "format code",
    "correct timezone handling",
    "implement middleware",
    "refactor service layer",
    "fix validation logic",
    "add caching layer",
    "improve error messages",
    "add input sanitization",
]

AUDIT_ACTIONS = [
    ("member.invited", "member"),
    ("repo.created", "repo"),
    ("commit.imported", "commit"),
    ("member.role_updated", "member"),
    ("repo.updated", "repo"),
    ("member.removed", "member"),
    ("team.settings_updated", "team"),
    ("repo.deleted", "repo"),
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _password_hash() -> str:
    """Generate a bcrypt password hash for seeded users.

    Uses a known password ("password123") so that any seeded Faker
    user can log in during development.  The hash is a proper bcrypt
    hash compatible with ``app.core.security.verify_password``.
    """
    return hash_password("password123")


def _generate_sha(seed_str: str) -> str:
    """Generate a deterministic 40-char SHA from a seed string."""
    return hashlib.sha1(seed_str.encode()).hexdigest()


def _random_commit_message() -> str:
    """Generate a random conventional-commit style message."""
    ctype = fake.random_element(COMMIT_TYPES)
    scope = fake.random_element(COMMIT_SCOPES)
    subject = fake.random_element(COMMIT_SUBJECTS)
    return f"{ctype}({scope}): {subject}"


def _slugify(name: str) -> str:
    """Create a URL-friendly slug from a name."""
    return name.lower().replace(" ", "-").replace(".", "")


# ---------------------------------------------------------------------------
# Clear
# ---------------------------------------------------------------------------


async def clear_existing_data(session: AsyncSession) -> None:
    """Delete all existing data in dependency order (child tables first)."""
    print("  Clearing existing data...")
    await session.execute(delete(AuditLog))
    await session.execute(delete(Commit))
    await session.execute(delete(RepoMember))
    await session.execute(delete(TeamMember))
    await session.execute(delete(Repo))
    await session.execute(delete(User))
    await session.execute(delete(Team))
    await session.flush()
    print("  All existing data cleared.")


# ---------------------------------------------------------------------------
# Seed steps
# ---------------------------------------------------------------------------


async def seed_teams(session: AsyncSession) -> list[Team]:
    """Seed teams with Faker-generated names. Returns list of Team objects."""
    teams: list[Team] = []
    used_slugs: set[str] = set()

    for i in range(1, NUM_TEAMS + 1):
        name = str(i)
        slug = f"team-{i}"
        used_slugs.add(slug)

        team = Team(id=uuid4(), name=name, slug=slug)
        session.add(team)
        teams.append(team)

    await session.flush()
    for team in teams:
        print(f"  Created team: {team.name} ({team.slug})")
    return teams


async def seed_users_and_members(
    session: AsyncSession,
    teams: list[Team],
) -> tuple[list[User], list[tuple[Team, User, str]]]:
    """Seed users and team memberships.

    Each team gets 5-10 unique users (no cross-team overlap).
    Returns (all_users, memberships).
    """
    all_users: list[User] = []
    memberships: list[tuple[Team, User, str]] = []
    now = datetime.now(UTC)

    for team in teams:
        num_members = fake.random_int(
            min=MIN_MEMBERS_PER_TEAM, max=MAX_MEMBERS_PER_TEAM
        )
        print(f"  Generating {num_members} members for {team.name}...")

        for i in range(num_members):
            name = fake.name()
            email = fake.unique.email()
            github = fake.unique.user_name()

            user = User(
                id=uuid4(),
                email=email,
                name=name,
                password_hash=_password_hash(),
                avatar_url=f"https://api.dicebear.com/7.x/identicon/png?seed={email}",
                github_username=github,
            )
            session.add(user)
            all_users.append(user)

            # Assign role: first member is admin, rest are weighted
            if i == 0:
                role = "admin"
            else:
                role = fake.random_element(ROLES[1:])  # developer or viewer

            tm = TeamMember(
                id=uuid4(),
                team_id=team.id,
                user_id=user.id,
                role=role,
                joined_at=now - timedelta(days=fake.random_int(min=1, max=90)),
            )
            session.add(tm)
            memberships.append((team, user, role))

    await session.flush()
    for team, user, role in memberships:
        print(f"    {user.name} ({user.email}) -> {team.name} as {role}")
    return all_users, memberships


async def seed_repos(
    session: AsyncSession,
    teams: list[Team],
) -> dict[str, list[Repo]]:
    """Seed 2-3 repos per team with Faker names. Returns team_slug -> repos."""
    repos_by_team: dict[str, list[Repo]] = {}

    for team in teams:
        num_repos = fake.random_int(min=MIN_REPOS_PER_TEAM, max=MAX_REPOS_PER_TEAM)
        team_repos: list[Repo] = []

        for _ in range(num_repos):
            # Generate a repo name from random words
            words = fake.words(nb=fake.random_int(min=2, max=3))
            repo_name = "-".join(words)
            url = f"https://github.com/{team.slug}/{repo_name}"

            repo = Repo(
                id=uuid4(),
                team_id=team.id,
                name=repo_name,
                url=url,
                description=fake.sentence(nb_words=6),
            )
            session.add(repo)
            team_repos.append(repo)

        repos_by_team[team.slug] = team_repos
        print(f"  Created {len(team_repos)} repos for {team.name}")

    await session.flush()
    return repos_by_team


async def seed_repo_members(
    session: AsyncSession,
    memberships: list[tuple[Team, User, str]],
    repos_by_team: dict[str, list[Repo]],
) -> None:
    """Add non-viewer members to their team's repos."""
    # Build team_id -> members map
    team_members: dict[str, list[tuple[User, str]]] = {}
    for team, user, role in memberships:
        team_members.setdefault(str(team.id), []).append((user, role))

    now = datetime.now(UTC)
    count = 0

    for team_slug, repos in repos_by_team.items():
        team_id = str(repos[0].team_id)
        members = team_members.get(team_id, [])
        for repo in repos:
            for user, team_role in members:
                if team_role == "viewer":
                    continue
                rm = RepoMember(
                    id=uuid4(),
                    repo_id=repo.id,
                    user_id=user.id,
                    role="developer",
                    added_at=now - timedelta(days=fake.random_int(min=1, max=60)),
                )
                session.add(rm)
                count += 1

    await session.flush()
    print(f"  Created {count} repo memberships")


async def seed_commits(
    session: AsyncSession,
    memberships: list[tuple[Team, User, str]],
    repos_by_team: dict[str, list[Repo]],
) -> int:
    """Seed 3-5 commits per developer, distributed across their team's repos.

    Viewers do not commit. Returns total commit count.
    """
    # Build team_id -> (team, developers) map
    team_devs: dict[str, list[tuple[Team, User]]] = {}
    for team, user, role in memberships:
        if role == "viewer":
            continue
        team_devs.setdefault(str(team.id), []).append((team, user))

    now = datetime.now(UTC)
    commit_count = 0

    for team_slug, repos in repos_by_team.items():
        team_id = str(repos[0].team_id)
        devs = team_devs.get(team_id, [])

        for team, user in devs:
            num_commits = fake.random_int(
                min=MIN_COMMITS_PER_DEVELOPER, max=MAX_COMMITS_PER_DEVELOPER
            )
            for n in range(num_commits):
                repo = fake.random_element(repos)
                seed_str = f"{team_slug}:{repo.name}:{user.email}:{n}:{uuid4()}"
                sha = _generate_sha(seed_str)

                commit = Commit(
                    id=uuid4(),
                    team_id=team.id,
                    user_id=user.id,
                    repo_id=repo.id,
                    sha=sha,
                    message=_random_commit_message(),
                    additions=fake.random_int(min=1, max=300),
                    deletions=fake.random_int(min=0, max=150),
                    ai_percentage=fake.random_int(min=0, max=80),
                    committed_at=now
                    - timedelta(
                        days=fake.random_int(min=0, max=30),
                        hours=fake.random_int(min=0, max=23),
                        minutes=fake.random_int(min=0, max=59),
                    ),
                )
                session.add(commit)
                commit_count += 1

    await session.flush()
    print(f"  Created {commit_count} commits")
    return commit_count


async def seed_audit_logs(
    session: AsyncSession,
    teams: list[Team],
    memberships: list[tuple[Team, User, str]],
) -> int:
    """Seed 2-4 audit logs per team. Returns total log count."""
    # Build team_id -> members map
    team_members: dict[str, list[User]] = {}
    for team, user, _role in memberships:
        team_members.setdefault(str(team.id), []).append(user)

    log_count = 0
    for team in teams:
        num_logs = fake.random_int(
            min=MIN_AUDIT_LOGS_PER_TEAM, max=MAX_AUDIT_LOGS_PER_TEAM
        )
        members = team_members.get(str(team.id), [])
        if not members:
            continue

        for _ in range(num_logs):
            actor = fake.random_element(members)
            action, resource = fake.random_element(AUDIT_ACTIONS)
            log = AuditLog(
                id=uuid4(),
                team_id=team.id,
                user_id=actor.id,
                action=action,
                resource=resource,
                details={
                    "description": fake.sentence(nb_words=8),
                    "team": team.name,
                    "actor": actor.name,
                    "timestamp": fake.iso8601(),
                },
            )
            session.add(log)
            log_count += 1

    await session.flush()
    print(f"  Created {log_count} audit logs")
    return log_count


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


async def seed_demo_user(
    session: AsyncSession,
    teams: list[Team],
) -> None:
    """Create a deterministic demo user for frontend development.

    Credentials match the hint shown on the login page:
        demo@smartdashboard.dev / demo-password-123
    """
    from sqlalchemy import select as _select

    existing = await session.execute(
        _select(User).where(User.email == "demo@smartdashboard.dev")
    )
    if existing.scalar_one_or_none() is not None:
        print("  Demo user already exists, skipping.")
        return

    demo_team = teams[0]
    user = User(
        id=uuid4(),
        email="demo@smartdashboard.dev",
        name="Demo User",
        password_hash=hash_password("demo-password-123"),
        avatar_url="https://api.dicebear.com/7.x/identicon/png?seed=demo",
        github_username="demo-user",
    )
    session.add(user)
    await session.flush()

    tm = TeamMember(
        id=uuid4(),
        team_id=demo_team.id,
        user_id=user.id,
        role="admin",
        joined_at=datetime.now(UTC),
    )
    session.add(tm)
    print("  Created demo user: demo@smartdashboard.dev (demo-password-123)")


async def main() -> None:
    """Run the seed script."""
    print("Seeding database with Faker-generated data...")
    print("=" * 60)

    async with AsyncSessionLocal() as session:
        async with session.begin():
            print("\n[1/8] Clearing existing data...")
            await clear_existing_data(session)

            print("\n[2/8] Seeding teams...")
            teams = await seed_teams(session)

            print("\n[3/8] Seeding users and memberships...")
            all_users, memberships = await seed_users_and_members(session, teams)

            print("\n[4/8] Seeding demo user...")
            await seed_demo_user(session, teams)

            print("\n[5/8] Seeding repos...")
            repos_by_team = await seed_repos(session, teams)

            print("\n[6/8] Seeding repo memberships...")
            await seed_repo_members(session, memberships, repos_by_team)

            print("\n[7/8] Seeding commits...")
            commit_count = await seed_commits(session, memberships, repos_by_team)

            print("\n[8/8] Seeding audit logs...")
            log_count = await seed_audit_logs(session, teams, memberships)

    print("\n" + "=" * 60)
    print("Database seeding complete!")
    print(f"  Teams: {len(teams)}")
    print(f"  Users: {len(all_users)}")
    total_repos = sum(len(r) for r in repos_by_team.values())
    print(f"  Repos: {total_repos}")
    print(f"  Commits: {commit_count}")
    print(f"  Audit logs: {log_count}")

    await engine.dispose()


if __name__ == "__main__":
    # On Windows, psycopg async requires SelectorEventLoop (not ProactorEventLoop)
    if sys.platform == "win32":
        from asyncio import WindowsSelectorEventLoopPolicy

        asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())
    asyncio.run(main())