/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户注册
         * @description Register a new user account.
         *
         *     - Email must be unique and valid.
         *     - Password must be at least 8 characters with uppercase, lowercase, and digit.
         *     - Returns the new user's id, email, and name (never the password hash).
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录
         * @description Authenticate a user and return JWT tokens.
         *
         *     - Accepts email and password.
         *     - Returns access_token (15 min) and refresh_token (7 days).
         *     - On failure, returns 401 with a generic message (no email enumeration).
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新 Access Token
         * @description Exchange a valid refresh token for a new access token.
         *
         *     - Validates the refresh token signature and expiry.
         *     - Enforces one-time use via a blacklist (rotation).
         *     - Replay of an old token invalidates the entire token family.
         *     - Expired refresh token returns 401 with "请重新登录".
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Members
         * @description Retrieve a paginated list of team members.
         */
        get: operations["list_members_api_v1_members_get"];
        put?: never;
        /**
         * Create Member
         * @description Create a new team member (admin only).
         */
        post: operations["create_member_api_v1_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Member
         * @description Retrieve a single member by ID.
         */
        get: operations["get_member_api_v1_members__member_id__get"];
        /**
         * Update Member
         * @description Update a member's information (admin only).
         */
        put: operations["update_member_api_v1_members__member_id__put"];
        post?: never;
        /**
         * Delete Member
         * @description Delete a member (admin only).
         */
        delete: operations["delete_member_api_v1_members__member_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 提交列表
         * @description 获取提交记录列表，支持分页和筛选。
         */
        get: operations["list_commits_api_v1_commits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commits/{commit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 提交详情
         * @description 获取单条提交记录详情。
         */
        get: operations["get_commit_api_v1_commits__commit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commits/workload/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 成员工作量统计
         * @description 获取指定成员的工作量统计。
         */
        get: operations["get_workload_api_v1_commits_workload__member_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CommitDetailResponse
         * @description Response schema for commit detail (includes team_id).
         */
        CommitDetailResponse: {
            /** Id */
            id: string;
            /** Team Id */
            team_id: string;
            /** Member Id */
            member_id: string;
            /** Sha */
            sha: string;
            /** Message */
            message: string;
            /** Repository */
            repository: string;
            /** Branch */
            branch: string;
            /** Lines Added */
            lines_added: number;
            /** Lines Deleted */
            lines_deleted: number;
            /** Ai Percentage */
            ai_percentage: number;
            /**
             * Committed At
             * Format: date-time
             */
            committed_at: string;
        };
        /**
         * CommitResponse
         * @description Response schema for a single commit.
         */
        CommitResponse: {
            /** Id */
            id: string;
            /** Member Id */
            member_id: string;
            /** Sha */
            sha: string;
            /** Message */
            message: string;
            /** Repository */
            repository: string;
            /** Branch */
            branch: string;
            /** Lines Added */
            lines_added: number;
            /** Lines Deleted */
            lines_deleted: number;
            /** Ai Percentage */
            ai_percentage: number;
            /**
             * Committed At
             * Format: date-time
             */
            committed_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Request body for user login.
         */
        LoginRequest: {
            /**
             * Email
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * Password
             * @description User password
             */
            password: string;
        };
        /**
         * MemberCreate
         * @description Request body for creating a member.
         * @example {
         *       "email": "zhangsan@example.com",
         *       "github_username": "zhangsan",
         *       "name": "张三",
         *       "role": "developer"
         *     }
         */
        MemberCreate: {
            /**
             * Name
             * @description Display name
             */
            name: string;
            /**
             * Email
             * Format: email
             * @description Email address
             */
            email: string;
            /** @description Team role */
            role: components["schemas"]["Role"];
            /**
             * Github Username
             * @description GitHub handle
             */
            github_username?: string | null;
        };
        /**
         * MemberResponse
         * @description Response schema for a single member.
         */
        MemberResponse: {
            /** Id */
            id: string;
            /** Team Id */
            team_id: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["Role"];
            /** Github Username */
            github_username: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MemberUpdate
         * @description Request body for updating a member.
         */
        MemberUpdate: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            role?: components["schemas"]["Role"] | null;
            /** Github Username */
            github_username?: string | null;
        };
        /** PageResponse[CommitResponse] */
        PageResponse_CommitResponse_: {
            /** Items */
            items: components["schemas"]["CommitResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PaginatedMembers
         * @description Paginated list of members.
         */
        PaginatedMembers: {
            /** Items */
            items: components["schemas"]["MemberResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * RefreshRequest
         * @description Request body for token refresh.
         */
        RefreshRequest: {
            /**
             * Refresh Token
             * @description A valid refresh token
             */
            refresh_token: string;
        };
        /**
         * RegisterRequest
         * @description Request body for user registration.
         */
        RegisterRequest: {
            /**
             * Email
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * Password
             * @description Password (min 8 chars, must include uppercase, lowercase, digit)
             */
            password: string;
            /**
             * Name
             * @description Display name
             * @example Alice Zhang
             */
            name: string;
            /**
             * Team Id
             * Format: uuid
             * @description Team to join
             */
            team_id: string;
        };
        /**
         * RegisterResponse
         * @description Response after successful registration.
         */
        RegisterResponse: {
            /**
             * Id
             * @description User UUID
             */
            id: string;
            /**
             * Email
             * @description User email
             */
            email: string;
            /**
             * Name
             * @description Display name
             */
            name: string;
        };
        /**
         * Role
         * @description Member role within a team.
         * @enum {string}
         */
        Role: "admin" | "developer" | "viewer";
        /**
         * SuccessResponse
         * @description Generic success response.
         */
        SuccessResponse: {
            /** Message */
            message: string;
        };
        /**
         * TokenResponse
         * @description Response after successful login containing JWT tokens.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description Short-lived JWT access token
             */
            access_token: string;
            /**
             * Refresh Token
             * @description Long-lived JWT refresh token
             */
            refresh_token: string;
            /**
             * Token Type
             * @description Token type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token expiry in seconds
             */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkloadResponse
         * @description Response schema for member workload statistics.
         */
        WorkloadResponse: {
            /** Member Id */
            member_id: string;
            /** User Id */
            user_id: string;
            /** Total Commits */
            total_commits: number;
            /** Total Lines Added */
            total_lines_added: number;
            /** Total Lines Deleted */
            total_lines_deleted: number;
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_members_get: {
        parameters: {
            query?: {
                /** @description 按角色筛选 */
                role?: components["schemas"]["Role"] | null;
                /** @description 按姓名模糊搜索 */
                name?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMembers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_member_api_v1_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_member_api_v1_members__member_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_v1_members__member_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_member_api_v1_members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_commits_api_v1_commits_get: {
        parameters: {
            query?: {
                /** @description 按成员筛选 */
                member_id?: string | null;
                /** @description 按仓库筛选 */
                repository?: string | null;
                /** @description 起始日期 */
                start_date?: string | null;
                /** @description 结束日期 */
                end_date?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_CommitResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_commit_api_v1_commits__commit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workload_api_v1_commits_workload__member_id__get: {
        parameters: {
            query?: {
                /** @description 起始日期 */
                start_date?: string | null;
                /** @description 结束日期 */
                end_date?: string | null;
            };
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
